CREATE DATABASE `{{DB_NAME}}`;

CREATE USER '{{DB_USER}}'@'%' IDENTIFIED BY '{{DB_PASS}}';

GRANT ALL PRIVILEGES ON `{{DB_NAME}}`.* TO '{{DB_USER}}'@'%';

ALTER USER '{{DB_USER}}'@'%' IDENTIFIED BY '{{DB_PASS}}';

ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ROOT_PASS}}';

FLUSH PRIVILEGES;