CREATE DATABASE IF NOT EXISTS %%DB_NAME%%;

GRANT ALL PRIVILEGES ON %%DB_NAME%%.* TO '%%DB_USER%%'@'%' IDENTIFIED BY '%%DB_PASS%%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '%%DB_PASS%%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
